/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V5_EXAMPLES_MEDIA_PLAYER_HPP_
#define V5_EXAMPLES_MEDIA_PLAYER_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>
#include <string>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v5 {
namespace examples {

class MediaPlayer {
public:
    virtual ~MediaPlayer() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
    struct Person : CommonAPI::Struct< std::string, std::string> {
    
        Person()
        {
            std::get< 0>(values_) = "";
            std::get< 1>(values_) = "";
        }
        Person(const std::string &_firstname, const std::string &_surname)
        {
            std::get< 0>(values_) = _firstname;
            std::get< 1>(values_) = _surname;
        }
        inline const std::string &getFirstname() const { return std::get< 0>(values_); }
        inline void setFirstname(const std::string &_value) { std::get< 0>(values_) = _value; }
        inline const std::string &getSurname() const { return std::get< 1>(values_); }
        inline void setSurname(const std::string &_value) { std::get< 1>(values_) = _value; }
        inline bool operator==(const Person& _other) const {
        return (getFirstname() == _other.getFirstname() && getSurname() == _other.getSurname());
        }
        inline bool operator!=(const Person &_other) const {
            return !((*this) == _other);
        }
    
    };
    struct TrackInfo : CommonAPI::Struct< std::string, std::string, Person, Person> {
    
        TrackInfo()
        {
            std::get< 0>(values_) = "";
            std::get< 1>(values_) = "";
            std::get< 2>(values_) = Person();
            std::get< 3>(values_) = Person();
        }
        TrackInfo(const std::string &_title, const std::string &_album, const Person &_composer, const Person &_interpret)
        {
            std::get< 0>(values_) = _title;
            std::get< 1>(values_) = _album;
            std::get< 2>(values_) = _composer;
            std::get< 3>(values_) = _interpret;
        }
        inline const std::string &getTitle() const { return std::get< 0>(values_); }
        inline void setTitle(const std::string &_value) { std::get< 0>(values_) = _value; }
        inline const std::string &getAlbum() const { return std::get< 1>(values_); }
        inline void setAlbum(const std::string &_value) { std::get< 1>(values_) = _value; }
        inline const Person &getComposer() const { return std::get< 2>(values_); }
        inline void setComposer(const Person &_value) { std::get< 2>(values_) = _value; }
        inline const Person &getInterpret() const { return std::get< 3>(values_); }
        inline void setInterpret(const Person &_value) { std::get< 3>(values_) = _value; }
        inline bool operator==(const TrackInfo& _other) const {
        return (getTitle() == _other.getTitle() && getAlbum() == _other.getAlbum() && getComposer() == _other.getComposer() && getInterpret() == _other.getInterpret());
        }
        inline bool operator!=(const TrackInfo &_other) const {
            return !((*this) == _other);
        }
    
    };
};

const char* MediaPlayer::getInterface() {
    return ("examples.MediaPlayer:v5_4");
}

CommonAPI::Version MediaPlayer::getInterfaceVersion() {
    return CommonAPI::Version(5, 4);
}


} // namespace examples
} // namespace v5

namespace CommonAPI {
}


// Compatibility
namespace v5_4 = v5;

#endif // V5_EXAMPLES_MEDIA_PLAYER_HPP_
