/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V5_EXAMPLES_Media_Player_STUB_DEFAULT_HPP_
#define V5_EXAMPLES_Media_Player_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v5/examples/MediaPlayerStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v5 {
namespace examples {

/**
 * Provides a default implementation for MediaPlayerStubRemoteEvent and
 * MediaPlayerStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT MediaPlayerStubDefault
    : public virtual MediaPlayerStub {
public:
    COMMONAPI_EXPORT MediaPlayerStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(MediaPlayer::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT MediaPlayerStubRemoteEvent* initStubAdapter(const std::shared_ptr< MediaPlayerStubAdapter> &_adapter) {
        CommonAPI::Stub<MediaPlayerStubAdapter, MediaPlayerStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual const ::v5::examples::MediaPlayer::TrackInfo &getCurrentTrackAttribute() {
        return currentTrackAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const ::v5::examples::MediaPlayer::TrackInfo &getCurrentTrackAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getCurrentTrackAttribute();
    }
    COMMONAPI_EXPORT virtual void setCurrentTrackAttribute(::v5::examples::MediaPlayer::TrackInfo _value) {
        const bool valueChanged = trySetCurrentTrackAttribute(std::move(_value));
        if (valueChanged) {
            fireCurrentTrackAttributeChanged(currentTrackAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual void setCurrentTrackAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v5::examples::MediaPlayer::TrackInfo _value) {
        (void)_client;
        setCurrentTrackAttribute(_value);
    }
    COMMONAPI_EXPORT virtual void play(const std::shared_ptr<CommonAPI::ClientId> _client, MediaPlayer::TrackInfo _track, playReply_t _reply) {
        (void)_client;
        (void)_track;
        std::string name = "";
        _reply(name);
    }
    COMMONAPI_EXPORT virtual void fireStopEvent(const ::v5::examples::MediaPlayer::TrackInfo &_info) {
        MediaPlayerStub::fireStopEvent(_info);
    }


protected:
    COMMONAPI_EXPORT virtual bool trySetCurrentTrackAttribute(::v5::examples::MediaPlayer::TrackInfo _value) {
        if (!validateCurrentTrackAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<MediaPlayerStubAdapter> stubAdapter = CommonAPI::Stub<MediaPlayerStubAdapter, MediaPlayerStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockCurrentTrackAttribute(true);
            valueChanged = (currentTrackAttributeValue_ != _value);
            currentTrackAttributeValue_ = std::move(_value);
            stubAdapter->lockCurrentTrackAttribute(false);
        } else {
            valueChanged = (currentTrackAttributeValue_ != _value);
            currentTrackAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateCurrentTrackAttributeRequestedValue(const ::v5::examples::MediaPlayer::TrackInfo &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual void onRemoteCurrentTrackAttributeChanged() {
        // No operation in default
    }
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual MediaPlayerStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(MediaPlayerStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }

        COMMONAPI_EXPORT virtual void onRemoteCurrentTrackAttributeChanged() {
            assert(defaultStub_ !=NULL);
            defaultStub_->onRemoteCurrentTrackAttributeChanged();
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetCurrentTrackAttribute(::v5::examples::MediaPlayer::TrackInfo _value) {
            assert(defaultStub_ !=NULL);
            return defaultStub_->trySetCurrentTrackAttribute(std::move(_value));
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetCurrentTrackAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v5::examples::MediaPlayer::TrackInfo _value) {
            (void)_client;
            return onRemoteSetCurrentTrackAttribute(_value);
        }

    private:
        MediaPlayerStubDefault *defaultStub_;
    };
protected:
    MediaPlayerStubDefault::RemoteEventHandler remoteEventHandler_;

private:

    ::v5::examples::MediaPlayer::TrackInfo currentTrackAttributeValue_ {};

    CommonAPI::Version interfaceVersion_;
};

} // namespace examples
} // namespace v5


// Compatibility
namespace v5_4 = v5;

#endif // V5_EXAMPLES_Media_Player_STUB_DEFAULT
