/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V5_EXAMPLES_Media_Player_PROXY_BASE_HPP_
#define V5_EXAMPLES_Media_Player_PROXY_BASE_HPP_

#include <v5/examples/MediaPlayer.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <string>
#include <vector>

#include <CommonAPI/Attribute.hpp>
#include <CommonAPI/Event.hpp>
#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v5 {
namespace examples {

class MediaPlayerProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::ObservableAttribute<::v5::examples::MediaPlayer::TrackInfo> CurrentTrackAttribute;
    typedef CommonAPI::Event<
        ::v5::examples::MediaPlayer::TrackInfo
    > StopEvent;

    typedef std::function<void(const CommonAPI::CallStatus&, const std::string&)> PlayAsyncCallback;

    virtual CurrentTrackAttribute& getCurrentTrackAttribute() = 0;
    virtual void play(MediaPlayer::TrackInfo _track, CommonAPI::CallStatus &_internalCallStatus, std::string &_name, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> playAsync(const MediaPlayer::TrackInfo &_track, PlayAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual StopEvent& getStopEvent() = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace examples
} // namespace v5


// Compatibility
namespace v5_4 = v5;

#endif // V5_EXAMPLES_Media_Player_PROXY_BASE_HPP_
