/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V5_EXAMPLES_Media_Player_PROXY_HPP_
#define V5_EXAMPLES_Media_Player_PROXY_HPP_

#include <v5/examples/MediaPlayerProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/AttributeExtension.hpp>
#include <CommonAPI/Factory.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v5 {
namespace examples {

template <typename ... _AttributeExtensions>
class MediaPlayerProxy
    : virtual public MediaPlayer,
      virtual public MediaPlayerProxyBase,
      virtual public _AttributeExtensions... {
public:
    MediaPlayerProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~MediaPlayerProxy();

    typedef MediaPlayer InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Returns the wrapper class that provides access to the attribute currentTrack.
     */
    virtual CurrentTrackAttribute& getCurrentTrackAttribute() {
        return delegate_->getCurrentTrackAttribute();
    }
    /**
     * Calls play with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void play(MediaPlayer::TrackInfo _track, CommonAPI::CallStatus &_internalCallStatus, std::string &_name, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls play with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> playAsync(const MediaPlayer::TrackInfo &_track, PlayAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Returns the wrapper class that provides access to the broadcast stop.
     */
    virtual StopEvent& getStopEvent() {
        return delegate_->getStopEvent();
    }



 private:
    std::shared_ptr< MediaPlayerProxyBase> delegate_;
};

typedef MediaPlayerProxy<> MediaPlayerProxyDefault;

namespace MediaPlayerExtensions {
    template <template <typename > class _ExtensionType>
    class CurrentTrackAttributeExtension {
     public:
        typedef _ExtensionType< MediaPlayerProxyBase::CurrentTrackAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< MediaPlayerProxyBase::CurrentTrackAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        CurrentTrackAttributeExtension(MediaPlayerProxyBase& proxy): attributeExtension_(proxy.getCurrentTrackAttribute()) {
        }
    
        inline extension_type& getCurrentTrackAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

} // namespace MediaPlayerExtensions

//
// MediaPlayerProxy Implementation
//
template <typename ... _AttributeExtensions>
MediaPlayerProxy<_AttributeExtensions...>::MediaPlayerProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< MediaPlayerProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< MediaPlayerProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
MediaPlayerProxy<_AttributeExtensions...>::~MediaPlayerProxy() {
}

template <typename ... _AttributeExtensions>
void MediaPlayerProxy<_AttributeExtensions...>::play(MediaPlayer::TrackInfo _track, CommonAPI::CallStatus &_internalCallStatus, std::string &_name, const CommonAPI::CallInfo *_info) {
    delegate_->play(_track, _internalCallStatus, _name, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> MediaPlayerProxy<_AttributeExtensions...>::playAsync(const MediaPlayer::TrackInfo &_track, PlayAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->playAsync(_track, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &MediaPlayerProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool MediaPlayerProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool MediaPlayerProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& MediaPlayerProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& MediaPlayerProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> MediaPlayerProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace examples
} // namespace v5

namespace CommonAPI {
template<template<typename > class _AttributeExtension>
struct DefaultAttributeProxyHelper< ::v5::examples::MediaPlayerProxy,
    _AttributeExtension> {
    typedef typename ::v5::examples::MediaPlayerProxy<
            ::v5::examples::MediaPlayerExtensions::CurrentTrackAttributeExtension<_AttributeExtension>
    > class_t;
};
}


// Compatibility
namespace v5_4 = v5;

#endif // V5_EXAMPLES_Media_Player_PROXY_HPP_
