/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V2_EXAMPLES_Media_Player_STUB_HPP_
#define V2_EXAMPLES_Media_Player_STUB_HPP_

#include <functional>
#include <sstream>




#include <v2/examples/MediaPlayer.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <string>
#include <vector>

#include <mutex>

#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v2 {
namespace examples {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service MediaPlayer. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class MediaPlayerStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual MediaPlayer {
 public:
    ///Notifies all remote listeners about a change of value of the attribute currentTrack.
    virtual void fireCurrentTrackAttributeChanged(const ::v2::examples::MediaPlayer::TrackInfo &currentTrack) = 0;


    virtual void deactivateManagedInstances() = 0;

    void lockCurrentTrackAttribute(bool _lockAccess) {
        if (_lockAccess) {
            currentTrackMutex_.lock();
        } else {
            currentTrackMutex_.unlock();
        }
    }

protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */
    std::recursive_mutex currentTrackMutex_;

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for MediaPlayer.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class MediaPlayerStubRemoteEvent
{
public:
    virtual ~MediaPlayerStubRemoteEvent() { }

    /// Verification callback for remote set requests on the attribute currentTrack
    virtual bool onRemoteSetCurrentTrackAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v2::examples::MediaPlayer::TrackInfo _value) = 0;
    /// Action callback for remote set requests on the attribute currentTrack
    virtual void onRemoteCurrentTrackAttributeChanged() = 0;
};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service MediaPlayer to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class MediaPlayerStub
    : public virtual CommonAPI::Stub<MediaPlayerStubAdapter, MediaPlayerStubRemoteEvent>
{
public:
    typedef std::function<void ()> playReply_t;

    virtual ~MediaPlayerStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 2);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// Provides getter access to the attribute currentTrack
    virtual const ::v2::examples::MediaPlayer::TrackInfo &getCurrentTrackAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireCurrentTrackAttributeChanged(::v2::examples::MediaPlayer::TrackInfo _value) {
    auto stubAdapter = CommonAPI::Stub<MediaPlayerStubAdapter, MediaPlayerStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireCurrentTrackAttributeChanged(_value);
    }
    void lockCurrentTrackAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<MediaPlayerStubAdapter, MediaPlayerStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockCurrentTrackAttribute(_lockAccess);
    }
    /// This is the method that will be called on remote calls on the method play.
    virtual void play(const std::shared_ptr<CommonAPI::ClientId> _client, MediaPlayer::TrackInfo _track, playReply_t _reply) = 0;


    using CommonAPI::Stub<MediaPlayerStubAdapter, MediaPlayerStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<MediaPlayerStubAdapter, MediaPlayerStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<MediaPlayerStubAdapter, MediaPlayerStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef MediaPlayerStubRemoteEvent RemoteEventType;
    typedef MediaPlayer StubInterface;
};

} // namespace examples
} // namespace v2


// Compatibility
namespace v2_4 = v2;

#endif // V2_EXAMPLES_Media_Player_STUB_HPP_
