
/*
 * This file was generated by BST IDL Generator.
 */

/* © Copyright  Black Sesame Technologies (Chengdu) Co., Ltd. 2021. All rights reserved.
 * This file contains proprietary information that is the sole intellectual property of
 * Black Sesame Technologies (Chengdu) Co., Ltd. No part of this material or its
 * documentation may be reproduced, distributed, transmitted, displayed or published in
 * any manner without the written permission of Black Sesame Technologies (Chengdu) Co.,
 * Ltd. Anyone who infringes on the copyright of Black Sesame Technologies (Chengdu) Co.,
 * Ltd. shall be held accountable by Black Sesame Technologies (Chengdu) Co., Ltd..
 */

// HelloServiceTest.cpp
#include "HelloServiceTest.h"

TEST_F(HelloServiceTest, openCamera_1_sync)
{
    CommonAPI::CallStatus _status;
    uint32_t _cameraID = 16;
    bool _ifConfig = false;
    uint32_t _openStatus;
    bool _isWrong;
    myProxy->openCamera(_cameraID, _ifConfig, _status, _openStatus, _isWrong);

    EXPECT_EQ(_openStatus, 2);
    EXPECT_EQ(_isWrong, true);
}

TEST_F(HelloServiceTest, openCamera_1_async)
{
    CommonAPI::CallStatus _status;
    uint32_t _cameraID = 16;
    bool _ifConfig = false;
    uint32_t _openStatus;
    bool _isWrong;
    auto fut = myProxy->openCameraAsync(
        _cameraID, _ifConfig, [&_status, &_openStatus, &_isWrong](auto status_, auto openStatus_, auto isWrong_) {
            _status = status_;
            _openStatus = openStatus_;
            _isWrong = isWrong_;
        });
    _status = fut.get();

    EXPECT_EQ(_openStatus, 2);
    EXPECT_EQ(_isWrong, true);
}

TEST_F(HelloServiceTest, openCamera_2_sync)
{
    CommonAPI::CallStatus _status;
    uint32_t _cameraID = 1;
    bool _ifConfig = true;
    uint32_t _openStatus;
    bool _isWrong;
    myProxy->openCamera(_cameraID, _ifConfig, _status, _openStatus, _isWrong);

    EXPECT_EQ(_openStatus, 1);
    EXPECT_EQ(_isWrong, false);
}

TEST_F(HelloServiceTest, openCamera_2_async)
{
    CommonAPI::CallStatus _status;
    uint32_t _cameraID = 1;
    bool _ifConfig = true;
    uint32_t _openStatus;
    bool _isWrong;
    auto fut = myProxy->openCameraAsync(
        _cameraID, _ifConfig, [&_status, &_openStatus, &_isWrong](auto status_, auto openStatus_, auto isWrong_) {
            _status = status_;
            _openStatus = openStatus_;
            _isWrong = isWrong_;
        });
    _status = fut.get();

    EXPECT_EQ(_openStatus, 1);
    EXPECT_EQ(_isWrong, false);
}

TEST_F(HelloServiceTest, openCamera_3_sync)
{
    CommonAPI::CallStatus _status;
    uint32_t _cameraID = 3;
    bool _ifConfig = true;
    uint32_t _openStatus;
    bool _isWrong;
    myProxy->openCamera(_cameraID, _ifConfig, _status, _openStatus, _isWrong);

    EXPECT_EQ(_openStatus, 1);
    EXPECT_EQ(_isWrong, false);
}

TEST_F(HelloServiceTest, openCamera_3_async)
{
    CommonAPI::CallStatus _status;
    uint32_t _cameraID = 3;
    bool _ifConfig = true;
    uint32_t _openStatus;
    bool _isWrong;
    auto fut = myProxy->openCameraAsync(
        _cameraID, _ifConfig, [&_status, &_openStatus, &_isWrong](auto status_, auto openStatus_, auto isWrong_) {
            _status = status_;
            _openStatus = openStatus_;
            _isWrong = isWrong_;
        });
    _status = fut.get();

    EXPECT_EQ(_openStatus, 1);
    EXPECT_EQ(_isWrong, false);
}

TEST_F(HelloServiceTest, name_1_ObservableAttribute_sync)
{
    CommonAPI::CallStatus _status;
    std::string _value;
    std::string requestValue("Bob");
    std::string responseValue;
    CommonAPI::CallStatus _callStatus;
    std::string changeVal;

    myProxy->getNameAttribute().getChangedEvent().subscribe([&changeVal](const std::string &val) {
        std::cout << "Received change message: " << val << std::endl;
        changeVal = val;
    });
    myProxy->getNameAttribute().setValue(requestValue, _callStatus, responseValue);
    myProxy->getNameAttribute().getValue(_status, _value);

    EXPECT_EQ(changeVal, std::string("Bob"));
    EXPECT_EQ(responseValue, std::string("Bob"));
    EXPECT_EQ(_value, std::string("Bob"));
}

TEST_F(HelloServiceTest, name_1_ObservableAttribute_async)
{
    CommonAPI::CallStatus _status;
    std::string _value;
    std::string requestValue("Bob");
    std::string responseValue;
    CommonAPI::CallStatus _callStatus;
    std::string changeVal;

    myProxy->getNameAttribute().getChangedEvent().subscribe([&changeVal](const std::string &val) {
        std::cout << "Received change message: " << val << std::endl;
        changeVal = val;
    });
    auto getFut = myProxy->getNameAttribute().setValueAsync(
        requestValue, [&_callStatus, &responseValue](const CommonAPI::CallStatus &callStatus, const std::string &val) {
            std::cout << "attribute's setValueAsync message: " << val << std::endl;
            _callStatus = callStatus;
            responseValue = val;
        });
    _callStatus = getFut.get();
    auto setFut = myProxy->getNameAttribute().getValueAsync(
        [&_status, &_value](const CommonAPI::CallStatus &callStatus, const std::string &val) {
            std::cout << "attribute's getValueAsync message: " << val << std::endl;
            _status = callStatus;
            _value = val;
        });
    _status = setFut.get();

    EXPECT_EQ(changeVal, std::string("Bob"));
    EXPECT_EQ(responseValue, std::string("Bob"));
    EXPECT_EQ(_value, std::string("Bob"));
}

TEST_F(HelloServiceTest, name_2_ObservableAttribute_sync)
{
    CommonAPI::CallStatus _status;
    std::string _value;
    std::string requestValue("World");
    std::string responseValue;
    CommonAPI::CallStatus _callStatus;
    std::string changeVal;

    myProxy->getNameAttribute().getChangedEvent().subscribe([&changeVal](const std::string &val) {
        std::cout << "Received change message: " << val << std::endl;
        changeVal = val;
    });
    myProxy->getNameAttribute().setValue(requestValue, _callStatus, responseValue);
    myProxy->getNameAttribute().getValue(_status, _value);

    EXPECT_EQ(changeVal, std::string("World"));
    EXPECT_EQ(responseValue, std::string("World"));
    EXPECT_EQ(_value, std::string("World"));
}

TEST_F(HelloServiceTest, name_2_ObservableAttribute_async)
{
    CommonAPI::CallStatus _status;
    std::string _value;
    std::string requestValue("World");
    std::string responseValue;
    CommonAPI::CallStatus _callStatus;
    std::string changeVal;

    myProxy->getNameAttribute().getChangedEvent().subscribe([&changeVal](const std::string &val) {
        std::cout << "Received change message: " << val << std::endl;
        changeVal = val;
    });
    auto getFut = myProxy->getNameAttribute().setValueAsync(
        requestValue, [&_callStatus, &responseValue](const CommonAPI::CallStatus &callStatus, const std::string &val) {
            std::cout << "attribute's setValueAsync message: " << val << std::endl;
            _callStatus = callStatus;
            responseValue = val;
        });
    _callStatus = getFut.get();
    auto setFut = myProxy->getNameAttribute().getValueAsync(
        [&_status, &_value](const CommonAPI::CallStatus &callStatus, const std::string &val) {
            std::cout << "attribute's getValueAsync message: " << val << std::endl;
            _status = callStatus;
            _value = val;
        });
    _status = setFut.get();

    EXPECT_EQ(changeVal, std::string("World"));
    EXPECT_EQ(responseValue, std::string("World"));
    EXPECT_EQ(_value, std::string("World"));
}

TEST_F(HelloServiceTest, firstBc_1_SelectiveBroadcast)
{
    CommonAPI::CallStatus _status;
    std::string _hi;

    myProxy->getFirstBcSelectiveEvent().subscribe([&_hi](const std::string &hi_) { _hi = hi_; });

    uint32_t _cameraID = 16;
    bool _ifConfig = false;
    uint32_t _openStatus;
    bool _isWrong;
    auto fut = myProxy->openCameraAsync(
        _cameraID, _ifConfig, [&_status, &_openStatus, &_isWrong](auto status_, auto openStatus_, auto isWrong_) {
            _status = status_;
            _openStatus = openStatus_;
            _isWrong = isWrong_;
        });
    _status = fut.get();
    EXPECT_EQ(_hi, std::string("hi! First selective broadcast!"));
}

TEST_F(HelloServiceTest, secondBc_1_Broadcast)
{
    CommonAPI::CallStatus _status;
    std::string _bye;

    myProxy->getSecondBcEvent().subscribe([&_bye](const std::string &bye_) { _bye = bye_; });

    uint32_t _cameraID = 1;
    bool _ifConfig = true;
    uint32_t _openStatus;
    bool _isWrong;
    auto fut = myProxy->openCameraAsync(
        _cameraID, _ifConfig, [&_status, &_openStatus, &_isWrong](auto status_, auto openStatus_, auto isWrong_) {
            _status = status_;
            _openStatus = openStatus_;
            _isWrong = isWrong_;
        });
    _status = fut.get();
    EXPECT_EQ(_bye, std::string("Bye! Second broadcast!"));
}
